Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"


  config.vm.network "forwarded_port", guest: 3306, host: 3406
  config.vm.network "forwarded_port", guest: 80, host: 8180
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  config.vm.network "forwarded_port", guest: 15672, host: 15672


#  config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"

  config.vm.provision :ansible do |ansible|
     ansible.playbook = "playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

end
